### ISSUE TITLE
[Bug] BalanceString comes rounded

### ISSUE THREAD

**Issue by andreujuanc** [BitGo/BitGoJS#1006] opened 2021-02-01 17:35 UTC
Hello, 

I just noticed this issue in my dev environment, and I haven't been able to see where the problem is. I suspect in the backend.

## Environment Details

* **Node Version:** 10
* **BitGoJS Version:** N/A (the call to get wallets https://api.bitgo.com/docs/#operation/v2.wallet.get does not touch the sdk. as per https://github.com/andreujuanc/BitGoJS/blob/master/modules/express/src/clientRoutes.ts#L869 
* **BitGo Environment:** testnet

## Expected Behavior
```
  balance: 58584981,
  confirmedBalance: 58584981,
  spendableBalance: 58584981,
  balanceString: '0.58584981',
  confirmedBalanceString: '58584981',
  spendableBalanceString: '58584981',
```

## Current Behavior
```
  balance: 58584981,
  confirmedBalance: 58584981,
  spendableBalance: 58584981,
  balanceString: '0.585850', <- HERE 😢 
  confirmedBalanceString: '58584981',
  spendableBalanceString: '58584981',
```

## Possible Solution
It is documented that the balance string should return native, in this case satoshis, and it also shuold never lose precision. And it's doing the opposite. 

## Steps to Reproduce
https://api.bitgo.com/docs/#operation/v2.wallet.get
Testnet Address: 2MzBEeH3xMfJwb2ycZfmgJdHUfuKLfcszLw
Wallet Label: 4ee87039-ce80-46db-b97f-95345b47c074

Ill keep trying to see if it's a problem on my side. Help is appreciated it none the less.

**Comment by tylerlevine** [comment] 2021-02-01 21:41
Yeah, this looks like a rounding issue in our backend. We'll look into it - thanks :+1:

**Comment by andreujuanc** [comment] 2021-02-03 10:11
@tylerlevine Very sorry, but I think it is a bug on my side. Did you repro it on yours?

**Comment by tylerlevine** [comment] 2021-02-04 01:21
I wasn't able to reproduce this, the wallet balances look ok on my end:
```
  "balance": 59717927,
  "confirmedBalance": 59717927,
  "spendableBalance": 59717927,
  "balanceString": "59717927",
  "confirmedBalanceString": "59717927",
  "spendableBalanceString": "59717927",
```

**Comment by tylerlevine** [comment] 2021-02-04 01:26
I'll close this ticket, as I think we have a resolution here and there's no evidence of issues on our end.

**Closed by tylerlevine** 2021-02-04 01:26 UTC
Labels: bug

**Comment by andreujuanc** [comment] 2021-02-04 09:58
@tylerlevine  Thanks! And sorry :)
